/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : ethernet1.h
**     Project     : MDIO_Enet_S32K148
**     Processor   : S32K148_144
**     Component   : enet
**     Version     : Component SDK_S32K14x_09, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32K14x_09
**     Compiler    : GNU C Compiler
**     Date/Time   : 2020-09-08, 16:32, # CodeGen: 0
**     Contents    :
**         ENET_DRV_GetDefaultConfig       - void ENET_DRV_GetDefaultConfig(enet_config_t * config);
**         ENET_DRV_Init                   - void ENET_DRV_Init(uint8_t instance,enet_state_t * state,const enet_config_t...
**         ENET_DRV_Deinit                 - void ENET_DRV_Deinit(uint8_t instance);
**         ENET_DRV_ReadFrame              - status_t ENET_DRV_ReadFrame(uint8_t instance,enet_buffer_t *...
**         ENET_DRV_ProvideRxBuff          - void ENET_DRV_ProvideRxBuff(uint8_t instance,enet_buffer_t * buff);
**         ENET_DRV_SendFrame              - status_t ENET_DRV_SendFrame(uint8_t instance,const enet_buffer_t * buff);
**         ENET_DRV_GetTransmitStatus      - status_t ENET_DRV_GetTransmitStatus(uint8_t instance,const enet_buffer_t *...
**         ENET_DRV_EnableMDIO             - void ENET_DRV_EnableMDIO(uint8_t instance,bool miiPreambleDisabled);
**         ENET_DRV_MDIORead               - status_t ENET_DRV_MDIORead(uint8_t instance,uint8_t phyAddr,uint8_t...
**         ENET_DRV_MDIOWrite              - status_t ENET_DRV_MDIOWrite(uint8_t instance,uint8_t phyAddr,uint8_t...
**         ENET_DRV_SetMacAddr             - void ENET_DRV_SetMacAddr(uint8_t instance,const uint8_t * macAddr);
**         ENET_DRV_GetMacAddr             - void ENET_DRV_GetMacAddr(uint8_t instance,uint8_t * macAddr);
**         ENET_DRV_SetUnicastForward      - void ENET_DRV_SetUnicastForward(uint8_t instance,const uint8_t * macAddr,bool...
**         ENET_DRV_SetMulticastForward    - void ENET_DRV_SetMulticastForward(uint8_t instance,const uint8_t *...
**         ENET_DRV_SetMulticastForwardAll - void ENET_DRV_SetMulticastForwardAll(uint8_t instance,bool enable);
**         ENET_DRV_SetSleepMode           - void ENET_DRV_SetSleepMode(uint8_t instance,bool enable);
**         ENET_DRV_ConfigCounters         - void ENET_DRV_ConfigCounters(uint8_t instance,bool enable);
**         ENET_DRV_GetCounter             - uint32_t ENET_DRV_GetCounter(uint8_t instance,enet_counter_t counter);
**         ENET_DRV_TimerInit              - void ENET_DRV_TimerInit(uint8_t instance,enet_timer_config_t * timerConfig);
**         ENET_DRV_TimerStart             - void ENET_DRV_TimerStart(uint8_t instance);
**         ENET_DRV_TimerStop              - void ENET_DRV_TimerStop(uint8_t instance);
**         ENET_DRV_TimerSet               - void ENET_DRV_TimerSet(uint8_t instance,uint32_t value);
**         ENET_DRV_TimerGet               - void ENET_DRV_TimerGet(uint8_t instance,uint32_t * value);
**         ENET_DRV_TimerSetCorrection     - void ENET_DRV_TimerSetCorrection(uint8_t instance,uint32_t value,uint32_t...
**         ENET_DRV_TimerEnableChannel     - void ENET_DRV_TimerEnableChannel(uint8_t instance,uint8_t...
**         ENET_DRV_TimerSetCompare        - void ENET_DRV_TimerSetCompare(uint8_t instance,uint8_t channel,uint32_t value);
**         ENET_DRV_TimerGetCapture        - void ENET_DRV_TimerGetCapture(uint8_t instance,uint8_t channel,uint32_t *...
**         ENET_DRV_TimerSetPulseWidth     - void ENET_DRV_TimerSetPulseWidth(uint8_t instance,uint8_t channel,uint8_t...
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016-2017 NXP
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file ethernet1.h
** @version 01.00
*/
/*!
**  @addtogroup ethernet1_module ethernet1 module documentation
**  @{
*/
#ifndef ethernet1_H
#define ethernet1_H
/* MODULE ethernet1. */

/* Include inherited beans */
#include "clockMan1.h"
#include "Cpu.h"

/*! @brief Device instance number */
#define INST_ETHERNET1 (0U)
/*! @brief Driver state structure which holds driver runtime data */
extern enet_state_t ethernet1_State;

/*! @brief The MAC address of the module */
extern uint8_t ethernet1_MacAddr[6];

/*! @brief Module configuration structures */
extern const enet_config_t ethernet1_InitConfig0;

/*! @brief Buffer configuration structures */
extern enet_buffer_config_t ethernet1_buffConfig0;

/*! @brief Module callbacks external declaration */


#endif
/* ifndef ethernet1_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the Freescale S32K series of microcontrollers.
**
** ###################################################################
*/

