/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : phy_cfg.c
**     Project     : MDIO_Enet_S32K148
**     Processor   : S32K148_144
**     Component   : phy
**     Version     : Component SDK_S32K14x_09, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32K14x_09
**     Compiler    : GNU C Compiler
**     Date/Time   : 2020-09-08, 16:32, # CodeGen: 0
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016-2017 NXP
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file phy_cfg.c
** @version 01.00
*/
/*!
**  @addtogroup phy_cfg_module phy_cfg module documentation
**  @{
*/

#include "phy_cfg.h"

#define PHY_TYPE_TJA110X (0U)

/*! @brief Array of pointers towards the driver structures */
phy_driver_t* phyDrivers[N_PHY_DRIVERS] = {&PHY_driver_tja110x};

/*! @brief Array of PHY configuration structures */
phy_config_t  phyConfig[N_PHY_DEVS] = {
    {
        .type = PHY_TYPE_TJA110X,
        .addr = 2,
        .location = PHY_LOCATION_EXTERNAL,
        .role = PHY_ROLE_MASTER,
        .enetInstance =  0,
        .linkUpEventCB = link_up,
        .linkDownEventCB = link_down,
        .autonegCompleteCB = NULL,
        .autonegFailedCB = NULL
    },
};

/* END phy1. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the Freescale S32K series of microcontrollers.
**
** ###################################################################
*/
